server:
  port: 8080
  servlet:
    context-path: /api

app:
  server-url: /api

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/applause_matcher?serverTimezone=Europe/Warsaw&useUnicode=true&characterEncoding=UTF-8
    username: applause_matcher
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true